CREATE DATABASE IF NOT EXISTS offermate DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE offermate;

CREATE TABLE IF NOT EXISTS sys_user (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(50) NOT NULL UNIQUE COMMENT '用户名',
    password VARCHAR(100) NOT NULL COMMENT '登录密码',
    phone VARCHAR(20) DEFAULT NULL COMMENT '手机号',
    avatar VARCHAR(255) DEFAULT NULL COMMENT '用户头像',
    role TINYINT NOT NULL DEFAULT 1 COMMENT '角色：1求职者 2招聘者 3管理员',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '状态：1正常 0禁用',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='系统用户表';

CREATE TABLE IF NOT EXISTS company (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT NOT NULL COMMENT '招聘者用户ID',
    company_name VARCHAR(100) NOT NULL COMMENT '企业名称',
    logo VARCHAR(255) DEFAULT NULL COMMENT '企业Logo',
    industry VARCHAR(50) DEFAULT NULL COMMENT '所属行业',
    scale VARCHAR(50) DEFAULT NULL COMMENT '公司规模',
    address VARCHAR(255) DEFAULT NULL COMMENT '企业地址',
    intro TEXT COMMENT '企业介绍',
    audit_status TINYINT NOT NULL DEFAULT 0 COMMENT '审核状态：0待审核 1通过 2拒绝',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_company_user (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='企业信息表';

CREATE TABLE IF NOT EXISTS job_position (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    company_id BIGINT NOT NULL COMMENT '企业ID',
    recruiter_id BIGINT NOT NULL COMMENT '招聘者ID',
    title VARCHAR(100) NOT NULL COMMENT '岗位名称',
    salary_min INT DEFAULT NULL COMMENT '最低薪资',
    salary_max INT DEFAULT NULL COMMENT '最高薪资',
    city VARCHAR(50) DEFAULT NULL COMMENT '工作城市',
    experience VARCHAR(50) DEFAULT NULL COMMENT '经验要求',
    education VARCHAR(50) DEFAULT NULL COMMENT '学历要求',
    tags VARCHAR(255) DEFAULT NULL COMMENT '技能标签',
    description TEXT COMMENT '岗位描述',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '岗位状态：1招聘中 0已下架',
    audit_status TINYINT NOT NULL DEFAULT 0 COMMENT '审核状态：0待审核 1通过 2拒绝',
    view_count INT NOT NULL DEFAULT 0 COMMENT '浏览量',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='岗位表';

CREATE TABLE IF NOT EXISTS resume (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT NOT NULL COMMENT '用户ID',
    title VARCHAR(100) NOT NULL COMMENT '简历名称',
    real_name VARCHAR(50) DEFAULT NULL COMMENT '姓名',
    phone VARCHAR(20) DEFAULT NULL COMMENT '电话',
    email VARCHAR(100) DEFAULT NULL COMMENT '邮箱',
    education VARCHAR(50) DEFAULT NULL COMMENT '学历',
    experience_year INT DEFAULT NULL COMMENT '工作年限',
    skill TEXT COMMENT '技能描述',
    project_exp TEXT COMMENT '项目经历',
    self_intro TEXT COMMENT '自我评价',
    is_default TINYINT NOT NULL DEFAULT 0 COMMENT '是否默认简历：1是 0否',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='在线简历表';

CREATE TABLE IF NOT EXISTS job_delivery (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT NOT NULL COMMENT '求职者ID',
    job_id BIGINT NOT NULL COMMENT '岗位ID',
    company_id BIGINT NOT NULL COMMENT '企业ID',
    resume_id BIGINT NOT NULL COMMENT '简历ID',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '投递状态：1已投递 2已查看 3感兴趣 4邀面试 5不合适 6已录用',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_user_job (user_id, job_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='岗位投递表';

ALTER TABLE sys_user COMMENT = '系统用户表';
ALTER TABLE sys_user
    MODIFY id BIGINT NOT NULL AUTO_INCREMENT,
    MODIFY username VARCHAR(50) NOT NULL COMMENT '用户名',
    MODIFY password VARCHAR(100) NOT NULL COMMENT '登录密码',
    MODIFY phone VARCHAR(20) DEFAULT NULL COMMENT '手机号',
    MODIFY avatar VARCHAR(255) DEFAULT NULL COMMENT '用户头像',
    MODIFY role TINYINT NOT NULL DEFAULT 1 COMMENT '角色：1求职者 2招聘者 3管理员',
    MODIFY status TINYINT NOT NULL DEFAULT 1 COMMENT '状态：1正常 0禁用',
    MODIFY create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    MODIFY update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE company COMMENT = '企业信息表';
ALTER TABLE company
    MODIFY id BIGINT NOT NULL AUTO_INCREMENT,
    MODIFY user_id BIGINT NOT NULL COMMENT '招聘者用户ID',
    MODIFY company_name VARCHAR(100) NOT NULL COMMENT '企业名称',
    MODIFY logo VARCHAR(255) DEFAULT NULL COMMENT '企业Logo',
    MODIFY industry VARCHAR(50) DEFAULT NULL COMMENT '所属行业',
    MODIFY scale VARCHAR(50) DEFAULT NULL COMMENT '公司规模',
    MODIFY address VARCHAR(255) DEFAULT NULL COMMENT '企业地址',
    MODIFY intro TEXT COMMENT '企业介绍',
    MODIFY audit_status TINYINT NOT NULL DEFAULT 0 COMMENT '审核状态：0待审核 1通过 2拒绝',
    MODIFY create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    MODIFY update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE job_position COMMENT = '岗位表';
SET @job_audit_status_count = (
    SELECT COUNT(*)
    FROM information_schema.COLUMNS
    WHERE TABLE_SCHEMA = DATABASE()
      AND TABLE_NAME = 'job_position'
      AND COLUMN_NAME = 'audit_status'
);
SET @job_audit_status_sql = IF(
    @job_audit_status_count = 0,
    'ALTER TABLE job_position ADD COLUMN audit_status TINYINT NOT NULL DEFAULT 0 COMMENT ''审核状态：0待审核 1通过 2拒绝'' AFTER status',
    'SELECT 1'
);
PREPARE job_audit_status_stmt FROM @job_audit_status_sql;
EXECUTE job_audit_status_stmt;
DEALLOCATE PREPARE job_audit_status_stmt;
ALTER TABLE job_position
    MODIFY id BIGINT NOT NULL AUTO_INCREMENT,
    MODIFY company_id BIGINT NOT NULL COMMENT '企业ID',
    MODIFY recruiter_id BIGINT NOT NULL COMMENT '招聘者ID',
    MODIFY title VARCHAR(100) NOT NULL COMMENT '岗位名称',
    MODIFY salary_min INT DEFAULT NULL COMMENT '最低薪资',
    MODIFY salary_max INT DEFAULT NULL COMMENT '最高薪资',
    MODIFY city VARCHAR(50) DEFAULT NULL COMMENT '工作城市',
    MODIFY experience VARCHAR(50) DEFAULT NULL COMMENT '经验要求',
    MODIFY education VARCHAR(50) DEFAULT NULL COMMENT '学历要求',
    MODIFY tags VARCHAR(255) DEFAULT NULL COMMENT '技能标签',
    MODIFY description TEXT COMMENT '岗位描述',
    MODIFY status TINYINT NOT NULL DEFAULT 1 COMMENT '岗位状态：1招聘中 0已下架',
    MODIFY audit_status TINYINT NOT NULL DEFAULT 0 COMMENT '审核状态：0待审核 1通过 2拒绝',
    MODIFY view_count INT NOT NULL DEFAULT 0 COMMENT '浏览量',
    MODIFY create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    MODIFY update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE resume COMMENT = '在线简历表';
ALTER TABLE resume
    MODIFY id BIGINT NOT NULL AUTO_INCREMENT,
    MODIFY user_id BIGINT NOT NULL COMMENT '用户ID',
    MODIFY title VARCHAR(100) NOT NULL COMMENT '简历名称',
    MODIFY real_name VARCHAR(50) DEFAULT NULL COMMENT '姓名',
    MODIFY phone VARCHAR(20) DEFAULT NULL COMMENT '电话',
    MODIFY email VARCHAR(100) DEFAULT NULL COMMENT '邮箱',
    MODIFY education VARCHAR(50) DEFAULT NULL COMMENT '学历',
    MODIFY experience_year INT DEFAULT NULL COMMENT '工作年限',
    MODIFY skill TEXT COMMENT '技能描述',
    MODIFY project_exp TEXT COMMENT '项目经历',
    MODIFY self_intro TEXT COMMENT '自我评价',
    MODIFY is_default TINYINT NOT NULL DEFAULT 0 COMMENT '是否默认简历：1是 0否',
    MODIFY create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    MODIFY update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE job_delivery COMMENT = '岗位投递表';
ALTER TABLE job_delivery
    MODIFY id BIGINT NOT NULL AUTO_INCREMENT,
    MODIFY user_id BIGINT NOT NULL COMMENT '求职者ID',
    MODIFY job_id BIGINT NOT NULL COMMENT '岗位ID',
    MODIFY company_id BIGINT NOT NULL COMMENT '企业ID',
    MODIFY resume_id BIGINT NOT NULL COMMENT '简历ID',
    MODIFY status TINYINT NOT NULL DEFAULT 1 COMMENT '投递状态：1已投递 2已查看 3感兴趣 4邀面试 5不合适 6已录用',
    MODIFY create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    MODIFY update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

CREATE TABLE IF NOT EXISTS chat_session (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    seeker_id BIGINT NOT NULL COMMENT '求职者ID',
    recruiter_id BIGINT NOT NULL COMMENT '招聘者ID',
    job_id BIGINT NOT NULL COMMENT '岗位ID',
    last_message VARCHAR(255) DEFAULT NULL COMMENT '最后一条消息',
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_session (seeker_id, recruiter_id, job_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='聊天会话表';

CREATE TABLE IF NOT EXISTS chat_message (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    session_id BIGINT NOT NULL COMMENT '会话ID',
    sender_id BIGINT NOT NULL COMMENT '发送人ID',
    receiver_id BIGINT NOT NULL COMMENT '接收人ID',
    content TEXT NOT NULL COMMENT '消息内容',
    msg_type TINYINT NOT NULL DEFAULT 1 COMMENT '消息类型：1文本',
    is_read TINYINT NOT NULL DEFAULT 0 COMMENT '是否已读：0未读 1已读',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    KEY idx_session_time (session_id, create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='聊天消息表';

CREATE TABLE IF NOT EXISTS ai_call_log (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT NOT NULL COMMENT '用户ID',
    module VARCHAR(50) NOT NULL COMMENT '功能模块',
    prompt TEXT COMMENT '输入内容',
    result TEXT COMMENT '输出内容',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '调用时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI调用日志表';

CREATE TABLE IF NOT EXISTS notification (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT NOT NULL COMMENT '用户ID',
    title VARCHAR(100) NOT NULL COMMENT '通知标题',
    content VARCHAR(255) NOT NULL COMMENT '通知内容',
    type TINYINT NOT NULL COMMENT '通知类型',
    is_read TINYINT NOT NULL DEFAULT 0 COMMENT '是否已读：0未读 1已读',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='通知表';

CREATE TABLE IF NOT EXISTS interview_invitation (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    seeker_id BIGINT NOT NULL COMMENT '求职者ID',
    recruiter_id BIGINT NOT NULL COMMENT '招聘者ID',
    company_id BIGINT NOT NULL COMMENT '企业ID',
    job_id BIGINT NOT NULL COMMENT '岗位ID',
    delivery_id BIGINT NOT NULL COMMENT '投递记录ID',
    interview_time DATETIME NOT NULL COMMENT '面试时间',
    address VARCHAR(255) DEFAULT NULL COMMENT '面试地址',
    contact_name VARCHAR(50) DEFAULT NULL COMMENT '联系人',
    contact_phone VARCHAR(20) DEFAULT NULL COMMENT '联系电话',
    remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '状态：1待确认 2已接受 3已拒绝 4已取消',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY idx_seeker_id (seeker_id),
    KEY idx_recruiter_id (recruiter_id),
    KEY idx_delivery_id (delivery_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='面试邀请表';

CREATE TABLE IF NOT EXISTS ai_interview_session (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT NOT NULL COMMENT '用户ID',
    job_id BIGINT NOT NULL COMMENT '岗位ID',
    resume_id BIGINT DEFAULT NULL COMMENT '简历ID',
    title VARCHAR(100) DEFAULT NULL COMMENT '会话标题',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '状态：1进行中 2已完成',
    total_score INT DEFAULT NULL COMMENT '总评分',
    report TEXT COMMENT '面试报告',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY idx_user_id (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI模拟面试会话表';

CREATE TABLE IF NOT EXISTS ai_interview_message (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    session_id BIGINT NOT NULL COMMENT '面试会话ID',
    role VARCHAR(20) NOT NULL COMMENT '角色：user/assistant/system',
    content TEXT NOT NULL COMMENT '消息内容',
    score INT DEFAULT NULL COMMENT '本轮评分',
    suggestion TEXT COMMENT '本轮建议',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    KEY idx_session_id (session_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI模拟面试消息表';

CREATE TABLE IF NOT EXISTS operation_log (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT DEFAULT NULL COMMENT '用户ID',
    username VARCHAR(50) DEFAULT NULL COMMENT '用户名',
    role TINYINT DEFAULT NULL COMMENT '角色',
    module VARCHAR(50) NOT NULL COMMENT '模块',
    operation VARCHAR(100) NOT NULL COMMENT '操作',
    method VARCHAR(255) DEFAULT NULL COMMENT '执行方法',
    request_uri VARCHAR(255) DEFAULT NULL COMMENT '请求路径',
    request_method VARCHAR(20) DEFAULT NULL COMMENT '请求方式',
    ip VARCHAR(50) DEFAULT NULL COMMENT 'IP地址',
    params TEXT COMMENT '请求参数',
    result TEXT COMMENT '返回结果',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '状态：1成功 0失败',
    error_msg TEXT COMMENT '错误信息',
    cost_time BIGINT DEFAULT NULL COMMENT '耗时毫秒',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    KEY idx_user_id (user_id),
    KEY idx_module (module),
    KEY idx_operation (operation),
    KEY idx_create_time (create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='操作日志表';

ALTER TABLE chat_session COMMENT = '聊天会话表';
ALTER TABLE chat_session
    MODIFY id BIGINT NOT NULL AUTO_INCREMENT,
    MODIFY seeker_id BIGINT NOT NULL COMMENT '求职者ID',
    MODIFY recruiter_id BIGINT NOT NULL COMMENT '招聘者ID',
    MODIFY job_id BIGINT NOT NULL COMMENT '岗位ID',
    MODIFY last_message VARCHAR(255) DEFAULT NULL COMMENT '最后一条消息',
    MODIFY update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE chat_message COMMENT = '聊天消息表';
ALTER TABLE chat_message
    MODIFY id BIGINT NOT NULL AUTO_INCREMENT,
    MODIFY session_id BIGINT NOT NULL COMMENT '会话ID',
    MODIFY sender_id BIGINT NOT NULL COMMENT '发送人ID',
    MODIFY receiver_id BIGINT NOT NULL COMMENT '接收人ID',
    MODIFY content TEXT NOT NULL COMMENT '消息内容',
    MODIFY msg_type TINYINT NOT NULL DEFAULT 1 COMMENT '消息类型：1文本',
    MODIFY is_read TINYINT NOT NULL DEFAULT 0 COMMENT '是否已读：0未读 1已读',
    MODIFY create_time DATETIME DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE ai_call_log COMMENT = 'AI调用日志表';
ALTER TABLE ai_call_log
    MODIFY id BIGINT NOT NULL AUTO_INCREMENT,
    MODIFY user_id BIGINT NOT NULL COMMENT '用户ID',
    MODIFY module VARCHAR(50) NOT NULL COMMENT '功能模块',
    MODIFY prompt TEXT COMMENT '输入内容',
    MODIFY result TEXT COMMENT '输出内容',
    MODIFY create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '调用时间';

ALTER TABLE notification COMMENT = '通知表';
ALTER TABLE notification
    MODIFY id BIGINT NOT NULL AUTO_INCREMENT,
    MODIFY user_id BIGINT NOT NULL COMMENT '用户ID',
    MODIFY title VARCHAR(100) NOT NULL COMMENT '通知标题',
    MODIFY content VARCHAR(255) NOT NULL COMMENT '通知内容',
    MODIFY type TINYINT NOT NULL COMMENT '通知类型',
    MODIFY is_read TINYINT NOT NULL DEFAULT 0 COMMENT '是否已读：0未读 1已读',
    MODIFY create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';

ALTER TABLE interview_invitation COMMENT = '面试邀请表';
ALTER TABLE interview_invitation
    MODIFY id BIGINT NOT NULL AUTO_INCREMENT,
    MODIFY seeker_id BIGINT NOT NULL COMMENT '求职者ID',
    MODIFY recruiter_id BIGINT NOT NULL COMMENT '招聘者ID',
    MODIFY company_id BIGINT NOT NULL COMMENT '企业ID',
    MODIFY job_id BIGINT NOT NULL COMMENT '岗位ID',
    MODIFY delivery_id BIGINT NOT NULL COMMENT '投递记录ID',
    MODIFY interview_time DATETIME NOT NULL COMMENT '面试时间',
    MODIFY address VARCHAR(255) DEFAULT NULL COMMENT '面试地址',
    MODIFY contact_name VARCHAR(50) DEFAULT NULL COMMENT '联系人',
    MODIFY contact_phone VARCHAR(20) DEFAULT NULL COMMENT '联系电话',
    MODIFY remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
    MODIFY status TINYINT NOT NULL DEFAULT 1 COMMENT '状态：1待确认 2已接受 3已拒绝 4已取消',
    MODIFY create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    MODIFY update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE ai_interview_session COMMENT = 'AI模拟面试会话表';
ALTER TABLE ai_interview_session
    MODIFY id BIGINT NOT NULL AUTO_INCREMENT,
    MODIFY user_id BIGINT NOT NULL COMMENT '用户ID',
    MODIFY job_id BIGINT NOT NULL COMMENT '岗位ID',
    MODIFY resume_id BIGINT DEFAULT NULL COMMENT '简历ID',
    MODIFY title VARCHAR(100) DEFAULT NULL COMMENT '会话标题',
    MODIFY status TINYINT NOT NULL DEFAULT 1 COMMENT '状态：1进行中 2已完成',
    MODIFY total_score INT DEFAULT NULL COMMENT '总评分',
    MODIFY report TEXT COMMENT '面试报告',
    MODIFY create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    MODIFY update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE ai_interview_message COMMENT = 'AI模拟面试消息表';
ALTER TABLE ai_interview_message
    MODIFY id BIGINT NOT NULL AUTO_INCREMENT,
    MODIFY session_id BIGINT NOT NULL COMMENT '面试会话ID',
    MODIFY role VARCHAR(20) NOT NULL COMMENT '角色：user/assistant/system',
    MODIFY content TEXT NOT NULL COMMENT '消息内容',
    MODIFY score INT DEFAULT NULL COMMENT '本轮评分',
    MODIFY suggestion TEXT COMMENT '本轮建议',
    MODIFY create_time DATETIME DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE operation_log COMMENT = '操作日志表';
ALTER TABLE operation_log
    MODIFY id BIGINT NOT NULL AUTO_INCREMENT,
    MODIFY user_id BIGINT DEFAULT NULL COMMENT '用户ID',
    MODIFY username VARCHAR(50) DEFAULT NULL COMMENT '用户名',
    MODIFY role TINYINT DEFAULT NULL COMMENT '角色',
    MODIFY module VARCHAR(50) NOT NULL COMMENT '模块',
    MODIFY operation VARCHAR(100) NOT NULL COMMENT '操作',
    MODIFY method VARCHAR(255) DEFAULT NULL COMMENT '执行方法',
    MODIFY request_uri VARCHAR(255) DEFAULT NULL COMMENT '请求路径',
    MODIFY request_method VARCHAR(20) DEFAULT NULL COMMENT '请求方式',
    MODIFY ip VARCHAR(50) DEFAULT NULL COMMENT 'IP地址',
    MODIFY params TEXT COMMENT '请求参数',
    MODIFY result TEXT COMMENT '返回结果',
    MODIFY status TINYINT NOT NULL DEFAULT 1 COMMENT '状态：1成功 0失败',
    MODIFY error_msg TEXT COMMENT '错误信息',
    MODIFY cost_time BIGINT DEFAULT NULL COMMENT '耗时毫秒',
    MODIFY create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
